package org.cmas.entities.cards;

/**
 * Created on Nov 16, 2015
 *
 * @author Alexander Petukhov
 */
public enum PersonalCardType {
    PRIMARY, NATIONAL, CHILDREN_DIVING,

    EXTENDED_RANGE, NITROX, NITROX_GASBLENDER, TRIMIX, TRIMIX_GASBLENDER, OXYGEN_ADMINISTATOR, REBREATHER,

    ALTITUDE_DIVER, APNOEA, CAVE, COMPRESSOR_OPERATOR, DISABLED_DIVING, DRY_SUIT, DRIFT_DIVING, GYMSWIMMING, HYDROBIKE,
    ICE_DIVING, INTRO_TO_SCUBA, NAVIGATION, NIGHT, PHOTO, RESCUE, SCOOTER, SELF_RESCUE, SIDE_MOUNT, SKILLS, SNORKEL, WRECK,

    SCIENTIFIC, UNDERWATER_ARCHAEOLOGY, UNDERWATER_GEOLOGY, FRESHWATER_BIOLOGY, OCEAN_DISCOVERY, MARINE_BIOLOGY, HERITAGE_DISCOVERY;

    public String getName(){
        return name();
    }
}
