
update countries set iso3166_1_alpha_2_code = 'AF'
where name = 'Afghanistan';
update countries set iso3166_1_alpha_2_code = 'ZA'
where name = 'South Africa';
update countries set iso3166_1_alpha_2_code = 'AL'
where name = 'Albania';
update countries set iso3166_1_alpha_2_code = 'DZ'
where name = 'Algeria';
update countries set iso3166_1_alpha_2_code = 'DE'
where name = 'Germany';

update countries set iso3166_1_alpha_2_code = 'AD'
where name = 'Andorra';
update countries set iso3166_1_alpha_2_code = 'AO'
where name = 'Angola';
update countries set iso3166_1_alpha_2_code = 'SA'
where name = 'Saudi Arabia';
update countries set iso3166_1_alpha_2_code = 'AR'
where name = 'Argentina';
update countries set iso3166_1_alpha_2_code = 'AM'
where name = 'Armenia';
update countries set iso3166_1_alpha_2_code = 'AU'
where name = 'Australia';
update countries set iso3166_1_alpha_2_code = 'AT'
where name = 'Austria';
update countries set iso3166_1_alpha_2_code = 'BS'
where name = 'Bahamas';
update countries set iso3166_1_alpha_2_code = 'BE'
where name = 'Belgium';
update countries set iso3166_1_alpha_2_code = 'BY'
where name = 'Belarus';
update countries set iso3166_1_alpha_2_code = 'BO'
where name = 'Bolivia';
update countries set iso3166_1_alpha_2_code = 'BA'
where name = 'Bosnia-Herzegovina';
update countries set iso3166_1_alpha_2_code = 'BR'
where name = 'Brazil';
delete from countries
where name = 'British West Indies';
update countries set iso3166_1_alpha_2_code = 'BG'
where name = 'Bulgaria';
update countries set iso3166_1_alpha_2_code = 'KH'
where name = 'Cambodia';
update countries set iso3166_1_alpha_2_code = 'CM'
where name = 'Cameroon';
update countries set iso3166_1_alpha_2_code = 'CA'
where name = 'Canada';
update countries set iso3166_1_alpha_2_code = 'CV', name = 'Cabo Verde'
where name = 'Cape Verde';
update countries set iso3166_1_alpha_2_code = 'CL'
where name = 'Chile';
update countries set iso3166_1_alpha_2_code = 'CN'
where name like 'China%';
update countries set iso3166_1_alpha_2_code = 'CY'
where name = 'Cyprus';
update countries set iso3166_1_alpha_2_code = 'CO'
where name = 'Colombia';
update countries set iso3166_1_alpha_2_code = 'KR'
where name = 'South Korea';
update countries set iso3166_1_alpha_2_code = 'CR'
where name = 'Costa Rica';
update countries set iso3166_1_alpha_2_code = 'HR'
where name = 'Croatia';
update countries set iso3166_1_alpha_2_code = 'CU'
where name = 'Cuba';
update countries set iso3166_1_alpha_2_code = 'DK'
where name = 'Denmark';
update countries set iso3166_1_alpha_2_code = 'DO'
where name = 'Dominican Rep';
update countries set iso3166_1_alpha_2_code = 'EG'
where name = 'Egypt';
update countries set iso3166_1_alpha_2_code = 'AE'
where name = 'Arab Emirates';
update countries set iso3166_1_alpha_2_code = 'EC'
where name = 'Ecuador';
update countries set iso3166_1_alpha_2_code = 'ES'
where name = 'Spain';
update countries set iso3166_1_alpha_2_code = 'EE'
where name = 'Estonia';
update countries set iso3166_1_alpha_2_code = 'US'
where name = 'United States of America';
update countries set iso3166_1_alpha_2_code = 'FI'
where name = 'Finland';
update countries set iso3166_1_alpha_2_code = 'MK', name = 'Republic of North Macedonia'
where name = 'Macedonia';
update countries set iso3166_1_alpha_2_code = 'FR'
where name = 'France';
update countries set iso3166_1_alpha_2_code = 'GE'
where name = 'Georgia';
update countries set iso3166_1_alpha_2_code = 'GB'
where name = 'Great Britain';
update countries set iso3166_1_alpha_2_code = 'GR'
where name = 'Greece';
update countries set iso3166_1_alpha_2_code = 'GU'
where name = 'Guam';
update countries set iso3166_1_alpha_2_code = 'HN'
where name = 'Honduras';
update countries set iso3166_1_alpha_2_code = 'HK'
where name = 'Hong Kong';
update countries set iso3166_1_alpha_2_code = 'HU'
where name = 'Hungary';
update countries set iso3166_1_alpha_2_code = 'IN'
where name = 'India';
update countries set iso3166_1_alpha_2_code = 'ID'
where name = 'Indonesia';
delete from countries
where name = 'International';
update countries set iso3166_1_alpha_2_code = 'IR'
where name = 'Iran';
update countries set iso3166_1_alpha_2_code = 'IE'
where name = 'Ireland';
update countries set iso3166_1_alpha_2_code = 'IL'
where name = 'Israel';
update countries set iso3166_1_alpha_2_code = 'IT'
where name = 'Italy';
update countries set iso3166_1_alpha_2_code = 'JP'
where name = 'Japan';
update countries set iso3166_1_alpha_2_code = 'JO'
where name = 'Jordan';
update countries set iso3166_1_alpha_2_code = 'KZ', name = 'Kazakhstan'
where name = 'Kazkhstan';
update countries set iso3166_1_alpha_2_code = 'KE'
where name = 'Kenya';
update countries set iso3166_1_alpha_2_code = 'KW'
where name = 'Kuwait';
update countries set iso3166_1_alpha_2_code = 'KG', name = 'Kyrgyzstan'
where name = 'Kyrgyz Republic';
update countries set iso3166_1_alpha_2_code = 'LV'
where name = 'Latvia';
update countries set iso3166_1_alpha_2_code = 'LB'
where name = 'Lebanon';
update countries set iso3166_1_alpha_2_code = 'LY'
where name = 'Libya';
update countries set iso3166_1_alpha_2_code = 'LI'
where name = 'Liechtenstein';
update countries set iso3166_1_alpha_2_code = 'LT'
where name = 'Lithuania';
update countries set iso3166_1_alpha_2_code = 'LU', name = 'Luxembourg'
where name = 'Luxembourg Gd Duchy';
update countries set iso3166_1_alpha_2_code = 'MG'
where name = 'Madagascar';
update countries set iso3166_1_alpha_2_code = 'MY'
where name = 'Malaysia';
update countries set iso3166_1_alpha_2_code = 'MV'
where name = 'Maldives';
update countries set iso3166_1_alpha_2_code = 'MT'
where name = 'Malta';
delete from countries
where name = 'Marianas';
update countries set iso3166_1_alpha_2_code = 'MA', name = 'Morocco'
where name = 'Marocco';
update countries set iso3166_1_alpha_2_code = 'MU'
where name = 'Mauritius';
update countries set iso3166_1_alpha_2_code = 'MX'
where name = 'Mexico';
update countries set iso3166_1_alpha_2_code = 'MD'
where name = 'Republic of Moldova';
update countries set iso3166_1_alpha_2_code = 'MC'
where name = 'Monaco';
update countries set iso3166_1_alpha_2_code = 'ME'
where name = 'Montenegro';
update countries set iso3166_1_alpha_2_code = 'NA'
where name = 'Namibia';
update countries set iso3166_1_alpha_2_code = 'NG'
where name = 'Nigeria';
update countries set iso3166_1_alpha_2_code = 'NO'
where name = 'Norway';
update countries set iso3166_1_alpha_2_code = 'NC'
where name = 'New Caledonia';
update countries set iso3166_1_alpha_2_code = 'NZ'
where name = 'New Zealand';
update countries set iso3166_1_alpha_2_code = 'OM'
where name = 'Oman';
update countries set iso3166_1_alpha_2_code = 'PK'
where name = 'Pakistan';
update countries set iso3166_1_alpha_2_code = 'PS'
where name = 'Palestine';
update countries set iso3166_1_alpha_2_code = 'PA'
where name = 'Panama';
update countries set iso3166_1_alpha_2_code = 'NL'
where name = 'The Netherlands';
update countries set iso3166_1_alpha_2_code = 'PE'
where name = 'Peru';
update countries set iso3166_1_alpha_2_code = 'PH'
where name = 'Philippines';
update countries set iso3166_1_alpha_2_code = 'PL'
where name = 'Poland';
update countries set iso3166_1_alpha_2_code = 'PF'
where name = 'French Polynesia';
update countries set iso3166_1_alpha_2_code = 'PR'
where name = 'Puerto Rico';
update countries set iso3166_1_alpha_2_code = 'PT'
where name = 'Portugal';
update countries set iso3166_1_alpha_2_code = 'QA'
where name = 'Qatar';
update countries set iso3166_1_alpha_2_code = 'RO', name= 'Romania'
where name = 'Rumania';
update countries set iso3166_1_alpha_2_code = 'RU'
where name = 'Russia';
update countries set iso3166_1_alpha_2_code = 'SM'
where name = 'San Marino';
update countries set iso3166_1_alpha_2_code = 'SV'
where name = 'El Salvador';
update countries set iso3166_1_alpha_2_code = 'SN'
where name = 'Senegal';
update countries set iso3166_1_alpha_2_code = 'RS'
where name = 'Serbia';
update countries set iso3166_1_alpha_2_code = 'SC'
where name = 'Seychelles';
update countries set iso3166_1_alpha_2_code = 'SG'
where name = 'Singapore';
update countries set iso3166_1_alpha_2_code = 'SK'
where name = 'Slovakia';
update countries set iso3166_1_alpha_2_code = 'SI'
where name = 'Slovenia';
update countries set iso3166_1_alpha_2_code = 'SD'
where name = 'Sudan';
update countries set iso3166_1_alpha_2_code = 'LK'
where name = 'Sri Lanka';
update countries set iso3166_1_alpha_2_code = 'SE'
where name = 'Sweden';
update countries set iso3166_1_alpha_2_code = 'CH'
where name = 'Switzerland';
update countries set iso3166_1_alpha_2_code = 'SY'
where name = 'Syria';
delete from countries
where name = 'Taipei Chinese';
update countries set iso3166_1_alpha_2_code = 'TZ'
where name = 'Tanzania';
update countries set iso3166_1_alpha_2_code = 'CZ'
where name = 'Czech Republic';
update countries set iso3166_1_alpha_2_code = 'TH'
where name = 'Thailand';
update countries set iso3166_1_alpha_2_code = 'TN'
where name = 'Tunisia';
update countries set iso3166_1_alpha_2_code = 'TR'
where name = 'Turkey';
update countries set iso3166_1_alpha_2_code = 'UA'
where name = 'Ukraine';
update countries set iso3166_1_alpha_2_code = 'UY'
where name = 'Uruguay';
update countries set iso3166_1_alpha_2_code = 'VE'
where name = 'Venezuela';
update countries set iso3166_1_alpha_2_code = 'VN'
where name = 'Viet Nam';
update countries set iso3166_1_alpha_2_code = 'ZW'
where name = 'Zimbabwe';
update countries set iso3166_1_alpha_2_code = 'TW'
where name = 'Republic of China';
delete from countries
where name = 'North Cyprus';








