INSERT into personal_card_types (id, deleted, name, version) values (1, false, 'primary', 1);
INSERT into countries (id, deleted, name, code, version) values (1, false, 'Serbia and Montenegro', 'SCG', 1);
INSERT into countries (id, deleted, name, code, version) values (2, false, 'Afghanistan', 'AFG', 1);
INSERT into countries (id, deleted, name, code, version) values (3, false, 'South Africa', 'RSA', 1);
INSERT into countries (id, deleted, name, code, version) values (4, false, 'Albania', 'ALB', 1);
INSERT into countries (id, deleted, name, code, version) values (5, false, 'Algeria', 'ALG', 1);
INSERT into countries (id, deleted, name, code, version) values (6, false, 'Germany', 'GER', 1);
INSERT into countries (id, deleted, name, code, version) values (7, false, 'Germany Democratic Rep', 'RDA', 1);
INSERT into countries (id, deleted, name, code, version) values (8, false, 'Germany Federal Rep', 'RFA', 1);
INSERT into countries (id, deleted, name, code, version) values (9, false, 'Andorra', 'AND', 1);
INSERT into countries (id, deleted, name, code, version) values (10, false, 'Angola', 'ANG', 1);
INSERT into countries (id, deleted, name, code, version) values (11, false, 'Saudi Arabia', 'KSA', 1);
INSERT into countries (id, deleted, name, code, version) values (12, false, 'Argentina', 'ARG', 1);
INSERT into countries (id, deleted, name, code, version) values (13, false, 'Armenia', 'ARM', 1);
INSERT into countries (id, deleted, name, code, version) values (14, false, 'Australia', 'AUS', 1);
INSERT into countries (id, deleted, name, code, version) values (15, false, 'Austria', 'AUT', 1);
INSERT into countries (id, deleted, name, code, version) values (16, false, 'Bahamas', 'BAH', 1);
INSERT into countries (id, deleted, name, code, version) values (17, false, 'Belgium', 'BEL', 1);
INSERT into countries (id, deleted, name, code, version) values (18, false, 'Belarus', 'BLR', 1);
INSERT into countries (id, deleted, name, code, version) values (19, false, 'Bolivia', 'BOL', 1);
INSERT into countries (id, deleted, name, code, version) values (20, false, 'Bosnia-Herzegovina', 'BIH', 1);
INSERT into countries (id, deleted, name, code, version) values (21, false, 'Brazil', 'BRA', 1);
INSERT into countries (id, deleted, name, code, version) values (22, false, 'British West Indies', 'BWI', 1);
INSERT into countries (id, deleted, name, code, version) values (23, false, 'Bulgaria', 'BUL', 1);
INSERT into countries (id, deleted, name, code, version) values (24, false, 'Cambodia', 'CAM', 1);
INSERT into countries (id, deleted, name, code, version) values (25, false, 'Cameroon', 'CMR', 1);
INSERT into countries (id, deleted, name, code, version) values (26, false, 'Canada', 'CAN', 1);
INSERT into countries (id, deleted, name, code, version) values (27, false, 'Cape Verde', 'CPV', 1);
INSERT into countries (id, deleted, name, code, version) values (28, false, 'Chile', 'CHI', 1);
INSERT into countries (id, deleted, name, code, version) values (29, false, 'China, P. R. of', 'CHN', 1);
INSERT into countries (id, deleted, name, code, version) values (30, false, 'Cyprus', 'CYP', 1);
INSERT into countries (id, deleted, name, code, version) values (31, false, 'Colombia', 'COL', 1);
INSERT into countries (id, deleted, name, code, version) values (32, false, 'South Korea', 'KOR', 1);
INSERT into countries (id, deleted, name, code, version) values (33, false, 'Costa Rica', 'CRC', 1);
INSERT into countries (id, deleted, name, code, version) values (34, false, 'Croatia', 'CRO', 1);
INSERT into countries (id, deleted, name, code, version) values (35, false, 'Cuba', 'CUB', 1);
INSERT into countries (id, deleted, name, code, version) values (36, false, 'Denmark', 'DEN', 1);
INSERT into countries (id, deleted, name, code, version) values (37, false, 'Dominican Rep', 'DOM', 1);
INSERT into countries (id, deleted, name, code, version) values (38, false, 'Egypt', 'EGY', 1);
INSERT into countries (id, deleted, name, code, version) values (39, false, 'Arab Emirates', 'UEA', 1);
INSERT into countries (id, deleted, name, code, version) values (40, false, 'Ecuador', 'ECU', 1);
INSERT into countries (id, deleted, name, code, version) values (41, false, 'Spain', 'ESP', 1);
INSERT into countries (id, deleted, name, code, version) values (42, false, 'Estonia', 'EST', 1);
INSERT into countries (id, deleted, name, code, version) values (43, false, 'United States of America', 'USA', 1);
INSERT into countries (id, deleted, name, code, version) values (44, false, 'Finland', 'FIN', 1);
INSERT into countries (id, deleted, name, code, version) values (45, false, 'Former Yugoslav Republic of Macedonia', 'MKD', 1);
INSERT into countries (id, deleted, name, code, version) values (46, false, 'France', 'FRA', 1);
INSERT into countries (id, deleted, name, code, version) values (47, false, 'Georgia', 'GEO', 1);
INSERT into countries (id, deleted, name, code, version) values (48, false, 'Great Britain', 'GBR', 1);
INSERT into countries (id, deleted, name, code, version) values (49, false, 'Greece', 'GRE', 1);
INSERT into countries (id, deleted, name, code, version) values (50, false, 'Guam', 'GUM', 1);
INSERT into countries (id, deleted, name, code, version) values (51, false, 'Honduras', 'HON', 1);
INSERT into countries (id, deleted, name, code, version) values (52, false, 'Hong Kong', 'HKG', 1);
INSERT into countries (id, deleted, name, code, version) values (53, false, 'Hungary', 'HUN', 1);
INSERT into countries (id, deleted, name, code, version) values (54, false, 'India', 'IND', 1);
INSERT into countries (id, deleted, name, code, version) values (55, false, 'Indonesia', 'INA', 1);
INSERT into countries (id, deleted, name, code, version) values (56, false, 'International', 'INT', 1);
INSERT into countries (id, deleted, name, code, version) values (57, false, 'Iran', 'IRI', 1);
INSERT into countries (id, deleted, name, code, version) values (58, false, 'Ireland', 'IRL', 1);
INSERT into countries (id, deleted, name, code, version) values (59, false, 'Israel', 'ISR', 1);
INSERT into countries (id, deleted, name, code, version) values (60, false, 'Italy', 'ITA', 1);
INSERT into countries (id, deleted, name, code, version) values (61, false, 'Japan', 'JPN', 1);
INSERT into countries (id, deleted, name, code, version) values (62, false, 'Jordan', 'JOR', 1);
INSERT into countries (id, deleted, name, code, version) values (63, false, 'Kazkhstan', 'KAZ', 1);
INSERT into countries (id, deleted, name, code, version) values (64, false, 'Kenya', 'KEN', 1);
INSERT into countries (id, deleted, name, code, version) values (65, false, 'Kuwait', 'KUW', 1);
INSERT into countries (id, deleted, name, code, version) values (66, false, 'Kyrgyz Republic', 'KGZ', 1);
INSERT into countries (id, deleted, name, code, version) values (67, false, 'Latvia', 'LAT', 1);
INSERT into countries (id, deleted, name, code, version) values (68, false, 'Lebanon', 'LIB', 1);
INSERT into countries (id, deleted, name, code, version) values (69, false, 'Libya', 'LBA', 1);
INSERT into countries (id, deleted, name, code, version) values (70, false, 'Liechtenstein', 'LIE', 1);
INSERT into countries (id, deleted, name, code, version) values (71, false, 'Lithuania', 'LTU', 1);
INSERT into countries (id, deleted, name, code, version) values (72, false, 'Luxembourg Gd Duchy', 'LUX', 1);
INSERT into countries (id, deleted, name, code, version) values (73, false, 'Madagascar', 'MAD', 1);
INSERT into countries (id, deleted, name, code, version) values (74, false, 'Malaysia', 'MAS', 1);
INSERT into countries (id, deleted, name, code, version) values (75, false, 'Maldives', 'MDV', 1);
INSERT into countries (id, deleted, name, code, version) values (76, false, 'Malta', 'MLT', 1);
INSERT into countries (id, deleted, name, code, version) values (77, false, 'Marianas', 'IMA', 1);
INSERT into countries (id, deleted, name, code, version) values (78, false, 'Marocco', 'MAR', 1);
INSERT into countries (id, deleted, name, code, version) values (79, false, 'Mauritius', 'MRI', 1);
INSERT into countries (id, deleted, name, code, version) values (80, false, 'Mexico', 'MEX', 1);
INSERT into countries (id, deleted, name, code, version) values (81, false, 'Republic of Moldova', 'MDA', 1);
INSERT into countries (id, deleted, name, code, version) values (82, false, 'Monaco', 'MON', 1);
INSERT into countries (id, deleted, name, code, version) values (83, false, 'Montenegro', 'MNE', 1);
INSERT into countries (id, deleted, name, code, version) values (84, false, 'Namibia', 'NAM', 1);
INSERT into countries (id, deleted, name, code, version) values (85, false, 'Nigeria', 'NGR', 1);
INSERT into countries (id, deleted, name, code, version) values (86, false, 'Norway', 'NOR', 1);
INSERT into countries (id, deleted, name, code, version) values (87, false, 'New Caledonia', 'NCL', 1);
INSERT into countries (id, deleted, name, code, version) values (88, false, 'New Zealand', 'NZL', 1);
INSERT into countries (id, deleted, name, code, version) values (89, false, 'Oman', 'OMA', 1);
INSERT into countries (id, deleted, name, code, version) values (90, false, 'Pakistan', 'PAK', 1);
INSERT into countries (id, deleted, name, code, version) values (91, false, 'Palestine', 'PLE', 1);
INSERT into countries (id, deleted, name, code, version) values (92, false, 'Panama', 'PAN', 1);
INSERT into countries (id, deleted, name, code, version) values (93, false, 'The Netherlands', 'NED', 1);
INSERT into countries (id, deleted, name, code, version) values (94, false, 'Peru', 'PER', 1);
INSERT into countries (id, deleted, name, code, version) values (95, false, 'Philippines', 'PHI', 1);
INSERT into countries (id, deleted, name, code, version) values (96, false, 'Poland', 'POL', 1);
INSERT into countries (id, deleted, name, code, version) values (97, false, 'French Polynesia', 'TAH', 1);
INSERT into countries (id, deleted, name, code, version) values (98, false, 'Puerto Rico', 'PUR', 1);
INSERT into countries (id, deleted, name, code, version) values (99, false, 'Portugal', 'POR', 1);
INSERT into countries (id, deleted, name, code, version) values (100, false, 'Qatar', 'QAT', 1);
INSERT into countries (id, deleted, name, code, version) values (101, false, 'Rumania', 'ROM', 1);
INSERT into countries (id, deleted, name, code, version) values (102, false, 'Russia', 'RUS', 1);
INSERT into countries (id, deleted, name, code, version) values (103, false, 'San Marino', 'SMR', 1);
INSERT into countries (id, deleted, name, code, version) values (104, false, 'El Salvador', 'ESA', 1);
INSERT into countries (id, deleted, name, code, version) values (105, false, 'Senegal', 'SEN', 1);
INSERT into countries (id, deleted, name, code, version) values (106, false, 'Serbia', 'SRB', 1);
INSERT into countries (id, deleted, name, code, version) values (107, false, 'Seychelles', 'SEY', 1);
INSERT into countries (id, deleted, name, code, version) values (108, false, 'Singapore', 'SIN', 1);
INSERT into countries (id, deleted, name, code, version) values (109, false, 'Slovakia', 'SVK', 1);
INSERT into countries (id, deleted, name, code, version) values (110, false, 'Slovenia', 'SLO', 1);
INSERT into countries (id, deleted, name, code, version) values (111, false, 'Dudan', 'SUD', 1);
INSERT into countries (id, deleted, name, code, version) values (112, false, 'Sri Lanka', 'SRI', 1);
INSERT into countries (id, deleted, name, code, version) values (113, false, 'Sweden', 'SWE', 1);
INSERT into countries (id, deleted, name, code, version) values (114, false, 'Switzerland', 'SUI', 1);
INSERT into countries (id, deleted, name, code, version) values (115, false, 'Syria', 'SYR', 1);
INSERT into countries (id, deleted, name, code, version) values (116, false, 'Taipei Chinese', 'TPE', 1);
INSERT into countries (id, deleted, name, code, version) values (117, false, 'Tanzania', 'TAN', 1);
INSERT into countries (id, deleted, name, code, version) values (118, false, 'Czech Republic', 'CZE', 1);
INSERT into countries (id, deleted, name, code, version) values (119, false, 'Thailand', 'THA', 1);
INSERT into countries (id, deleted, name, code, version) values (120, false, 'Tunisia', 'TUN', 1);
INSERT into countries (id, deleted, name, code, version) values (121, false, 'Turkey', 'TUR', 1);
INSERT into countries (id, deleted, name, code, version) values (122, false, 'Ukrainia', 'UKR', 1);
INSERT into countries (id, deleted, name, code, version) values (123, false, 'USSR', 'URS', 1);
INSERT into countries (id, deleted, name, code, version) values (124, false, 'Uruguay', 'URU', 1);
INSERT into countries (id, deleted, name, code, version) values (125, false, 'Venezuela', 'VEN', 1);
INSERT into countries (id, deleted, name, code, version) values (126, false, 'Viet Nam', 'VIE', 1);
INSERT into countries (id, deleted, name, code, version) values (127, false, 'Yugoslavia', 'YUG', 1);
INSERT into countries (id, deleted, name, code, version) values (128, false, 'Zimbabwe', 'ZIM', 1);
INSERT into countries (id, deleted, name, code, version) values (129, false, 'Republic of China', 'TWN', 1);
INSERT into countries (id, deleted, name, code, version) values (130, false, 'North Cyprus', 'NCYP', 1);
